In [2]:
import pandas as pd
import numpy as np

### INTRO

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv")

In [4]:
np.shape(df)
np.ndim(df)
np.size(df)

25920

In [5]:
# Numpy allows several mathematical operations to be performed on them
# Operations are faster
# Hold just one type of data

In [6]:
# Initialize an array (one dimensional)
a = np.array([1,2,3], dtype='int16') # An array

In [7]:
# Initialize a array (2D)
b = np.array([[1,2,3], [3,2,1]]) # 2d array
print(b.shape)

(2, 3)


In [8]:
# Get Dimension (1 = One Dimension, 2 = Two Dimension)
a.ndim
b.ndim

2

In [9]:
# Get The Shape - a vector (unit = size)
a.shape # (3,)
b.shape # (2, 3)

(2, 3)

In [10]:
# Get Type 
a.dtype

dtype('int16')

In [11]:
# Get Size (bytes)
a.itemsize

2

In [12]:
# Get total size
a.nbytes

6

### Accessing/Changing Specific Element, Rows, Columns

In [13]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [14]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [15]:
# Get Specific Element [r, c
print(a[1, 5])

13


In [16]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
# Get a specific colum
a[:, 2]

array([ 3, 10])

In [18]:
# Fetch a list of element
# [start index : end index : step size]
a[:, 3:6] 

array([[ 4,  5,  6],
       [11, 12, 13]])

In [19]:
a[0, 1:6:2]

array([2, 4, 6])

In [20]:
# Change a single row value
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [21]:
# Change multiple row values
a[:, 2] = [13, 14]
print(a)

[[ 1  2 13  4  5  6  7]
 [ 8  9 14 11 12 20 14]]


In [22]:
# 3D EXAMPLE

arr_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

print(arr_3d)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [23]:
reshaped = arr_3d.flatten() 
reshaped

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [24]:
# Get specific element on 3d (work outside in)
# Fecth me value 5
print(arr_3d[0, 1, 1])

5


In [25]:
# Fetch me value 10
print(arr_3d[1, 1, 0])

10


In [26]:
# Updating a  3D Array value
# Fecth the array index first, then change

'''
- 1st dimension → depth (like multiple layers)
- 2nd dimension → rows
- 3rd dimension → columns
'''

arr_3d[:, 1, 2] = [11,13]
print(arr_3d)

[[[ 1  2  3]
  [ 4  5 11]]

 [[ 7  8  9]
  [10 11 13]]]


### Intializing different types of arrays

In [27]:
# All 0s matrix
np.zeros((4,3), dtype='int16')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [28]:
# All 1s matrix
np.ones((4,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [29]:
# Any other number
# np.full((matrix shape), the number)

np.full((4,3), 80)

array([[80, 80, 80],
       [80, 80, 80],
       [80, 80, 80],
       [80, 80, 80]])

In [30]:
# Any other number (full_like)
# Makes us reuse a shape
np.full_like(arr_3d, 4)

array([[[4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4]]])

In [31]:
# Any random number (float)
np.random.rand(4, 2, 3)

array([[[0.07722231, 0.23702727, 0.59751275],
        [0.94865255, 0.87935367, 0.60201082]],

       [[0.65299868, 0.8856814 , 0.10724498],
        [0.87507479, 0.9521906 , 0.80638436]],

       [[0.00122379, 0.33979315, 0.58207659],
        [0.17326429, 0.21843934, 0.97932587]],

       [[0.02866417, 0.31600713, 0.27639408],
        [0.12665093, 0.46126811, 0.28602856]]])

In [48]:
# Arithmetic with random array
# np.random.randint(7, size = (3,5)) + 16.3

np.random.randint(low = 18, high = 100, size = (5, 6), )

array([[49, 26, 77, 84, 29, 82],
       [77, 42, 47, 78, 42, 33],
       [40, 36, 60, 31, 79, 37],
       [34, 69, 69, 64, 34, 70],
       [53, 28, 33, 84, 72, 59]], dtype=int32)

In [50]:
# Any random number (integer)
np.random.randint(7, size = (3, 3), dtype = 'int16')

array([[5, 6, 5],
       [3, 0, 2],
       [0, 4, 6]], dtype=int16)

In [34]:
# Fixed Random Number: seed()
# np.random.seed(2)
np.random.rand(5,2)

array([[0.00575793, 0.24293578],
       [0.75256908, 0.04700687],
       [0.8129265 , 0.17077215],
       [0.24712044, 0.48185741],
       [0.82770396, 0.48071495]])

In [49]:
# Identity Matrix - Square matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [37]:
output = np.ones((5,5))
z = np.zeros((3,3))

z[1,1] = 9
print(z)

output[1:4, 1:4] = z
print(output)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Element-wise operation

In [38]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
10 + a * 2 ** 2

array([10, 14, 18, 22, 26, 30, 34, 38, 42, 46])

### Comparison operations

In [40]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a != 2

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True])

### Summarizing Opeartions

In [42]:
a.std()

np.float64(2.8722813232690143)

In [43]:
a.min()

np.int64(0)

In [44]:
a.max()

np.int64(9)

In [45]:
x = [1,2,3]
y = x
y[0] = -1
print(x)

[-1, 2, 3]
