In [43]:
def multiLine():
    print()
    print()

In [44]:
import numpy as np

In [45]:
vector = np.array([1,2,3,4,5,6,7,8,9])
matrix = np.array([[1,2,3], [4,5,6]])

print(vector)
print(matrix)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]]


## Array Rules

In [46]:
# - All data in an array must be of the same data type
# - The shape of an array can't be changed once created
# - We can't append to or remove from an original array 
# - An array must have equal number of columns
# - Arrays are 0 indexed and can be sliced

In [47]:
new_vector = np.append(vector, [10, 11, 12])
print(new_vector)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [48]:
# This will return an error, uneuqual column
# testing_prediction = np.array([[1,2,3], [4,5]])

In [49]:
# - This creates a VIEW which modify the original array
arr = np.array(
    [1,2,3,4,5]
    )
arr_slice = arr[:3]

arr_slice[0] = 99
print(arr_slice)
print(arr)

[99  2  3]
[99  2  3  4  5]


## 2DIMENSIONAL ARRAYS

In [50]:
matrix = np.array(
    [
        [1,2,3],
        [3,4,5],
        [5,6,7]
    ]
    )
print(matrix)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [51]:
# Accesing the value number 5
print(matrix[1,2])

# Accesing the value number 6
print(matrix[2,1])

5
6


## TYPES OF ARRAY
##### 0-D array = Scalar
##### 1-D array = Vector
##### 2-D array = Matrix
##### N-D array = Tensor (N means any number greater than 2)

In [52]:
# Creating a 2D array
arr = np.array(
        [
            [1,2,3], 
            [4,5,6]], dtype=np.int16
        )

# Getting the number of dimension of an array (ndim)
print(f"Dimenmsion: {arr.ndim}")

# Getting the number of shape of an array (shape) (row,column)
print(f"Shape: {arr.shape}")

# Getting the number of size of an array (size) - total element
print(f"Size: {arr.size}")

# Getting the number of type of an array (size) - datatype
print(f"Type: {arr.dtype}")

Dimenmsion: 2
Shape: (2, 3)
Size: 6
Type: int16


### Array Special Methods

In [ ]:
# Getting the zeros array
zeros = np.zeros(10)

# 2D ARRAY
new_zeros = np.zeros((3, 5), dtype=np.int16)
print(new_zeros)

multiLine()
# Getting the ones array - TENSOR
ones = np.ones((3, 5, 2), dtype=int)
print(ones)

multiLine()
# Generate a 64bit random numbers on the current state of memory
empty = np.empty((3,5), dtype=np.int64)
print(empty)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


[[[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]]
3


[[           0            0            0            0            0]
 [           0            0            0            0            0]
 [           0            0            0            0 538437165114]]


In [54]:
print(np.arange(10)) # Generate numbers from zero to the specified value
print(np.arange(4,10)) # Generate numbers from 4 to the 9
print(np.arange(0, 20, 2)) # Start from 0, skip 2, stop at 20

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


### **Linear Space**

In [55]:
line_space = np.linspace(1, 20, num=20, endpoint=True, retstep=False, dtype=int) # Generate numbers from zero to the specified value
print(line_space)


# start: The beginning value of the sequence.
# stop: The end value of the sequence. This value is included by default, unless endpoint is set to False.
# num (optional): The number of samples/values to generate. The default is 50.
# endpoint (optional): A boolean value. If True (default), the stop value is included. If False, it is not included.
# retstep (optional): If True, the function also returns the calculated step size between samples as a second output in a 
# tuple.

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


### Add, Remove and Sort, Reshape Element

In [56]:
arr = np.array(
    [1,2,5,3,4]
    )
print(np.sort(arr))

# This sort the array IN PlACE (permanently)
arr.sort()
print(arr)

[1 2 3 4 5]
[1 2 3 4 5]


### Concatenate 2 or  more arrays

In [57]:
a = np.arange(5, dtype=int)
b = np.arange(5, 10, dtype=int)
c = np.arange(10, 15, dtype=int)

print(np.concatenate((a, b, c))) # The variable must be converted to an iterable (tuple, list) else error
print(np.concatenate([a, b, c]))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


### Reshape

In [58]:
arr = np.arange(1, 10, dtype=int) #This generates 1,2,3,4,5,6,7,8,9 = 9 element
print(f"Original: {arr}")

# To reshape: product must equal total element

print(f"Reshaped 1: {arr.reshape(3, 3)}") # 3 x 3 = 9
print(f"Reshaped 2: {arr.reshape(9, 1)}") # 9 x 1 = 9
print(f"Reshaped 3: {arr.reshape(1, 9)}") # 1 x 9 = 9

# Creating a 3D Array
arr = np.arange(27, dtype=int)
print(f"3D : {arr.reshape(3, 3, 3)}")
print(f"3D : {arr.reshape(1,9,3)}")
print(f"3D : {arr.reshape(9,1,3)}")

# Indexing a reshaped array
target = arr.reshape(9,1,3)
print(target[5,0,1])

Original: [1 2 3 4 5 6 7 8 9]
Reshaped 1: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped 2: [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
Reshaped 3: [[1 2 3 4 5 6 7 8 9]]
3D : [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
3D : [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]]]
3D : [[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]

 [[12 13 14]]

 [[15 16 17]]

 [[18 19 20]]

 [[21 22 23]]

 [[24 25 26]]]
16


### Adding New Axis To An Array, Slicing, Indexing

In [59]:
# Increase the dimension of an array
arr = np.arange(3)
print(arr[np.newaxis, :]) # Increase the column
print(arr[:, np.newaxis]) # Increase the row


# expand_dims adds a new axis (0 = row, 1 = column)
expanded = np.expand_dims(arr, axis=0)
print(expanded)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]]


In [60]:
# Slicing and Indexing
arr = np.arange(20, dtype=int)
# print(arr[0])
# print(arr[-1])
# print(arr[3:5])
# print(arr[::2])

# We can specify a condition for the return value
print(arr[arr % 2 == 0])
print(arr[arr % 2 == 1])
print(arr[arr < 3])
print(arr[arr > 10])

# Chained condition
print(arr[(arr % 2 == 0) & (arr > 10)])

# -------------------------------------
# -------------------------------------

arr = np.arange(20, dtype=int)
conditional = (arr % 2 == 0) | (arr == 15)
print(conditional)

# -------------------------------------
# -------------------------------------
# Non-Zero
matrix = np.arange(20, dtype=np.int16)
reshaped = np.reshape(matrix, (5, 4))
print(reshaped)
print((np.nonzero(reshaped % 2 == 0))) # Returns rows and columns that met requirement
print((np.nonzero(reshaped % 2 == 100))) # No condition met

[ 0  2  4  6  8 10 12 14 16 18]
[ 1  3  5  7  9 11 13 15 17 19]
[0 1 2]
[11 12 13 14 15 16 17 18 19]
[12 14 16 18]
[ True False  True False  True False  True False  True False  True False
  True False  True  True  True False  True False]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
(array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4]), array([0, 2, 0, 2, 0, 2, 0, 2, 0, 2]))
(array([], dtype=int64), array([], dtype=int64))


In [61]:
# Creating A STACK
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
print(np.hstack([a, b])) # Horizontal Stack
print()
print(np.vstack([a, b])) # Vertical Stack

[[1 2 5 6]
 [3 4 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [62]:
# Creating a Copy of an array using the .copy() method

arr = np.arange(10)
new_arr = arr[3:6]
new_arr[0] = 999

print(arr)
print(new_arr)

arr = np.arange(10)
new_arr = arr[3:6].copy()
new_arr[0] = 999

print(arr)
print(new_arr)

[  0   1   2 999   4   5   6   7   8   9]
[999   4   5]
[0 1 2 3 4 5 6 7 8 9]
[999   4   5]


In [63]:
# Arithmetic Calcullation
def lineSpace():
    print()
    print()

first = np.array([1,2,3])
second = np.array([4,5,6])

print(first + second)
print(first - second)
print(first / second)
print(first * second)
print(first ** second)
lineSpace()
# -------------------------
# -------------------------
matrix = np.array([[1,2,3], [4,5,6]])
print(matrix)
lineSpace()
print(f"Sum: {np.sum(matrix, axis=0)}")
print(f"Product: {np.prod(matrix, axis=0)}")

[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[ 4 10 18]
[  1  32 729]


[[1 2 3]
 [4 5 6]]


Sum: [5 7 9]
Product: [ 4 10 18]


In [64]:
# Broadcasting
# Multipliying unequal array

data = np.array([[1,2,3], [4,5,6]])
print(data * 3)

# -------------------------------
# THIS RETURNS AN ERROR ValueError:
# Unequal matrix size and shape

new_data = np.array([[1,2,3], [4,5,6]])
multiplier = np.array([[1,2]])
print(new_data * multiplier)
# -------------------------------


[[ 3  6  9]
 [12 15 18]]


ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 

In [ ]:
age = np.array([82,93,98,89,88])
print(f"Max age: {age.max()}")
print(f"Min age: {age.min()}")
print(f"Sum: {age.sum()}")
print(f"Mean: {age.mean()}")
print(f"STD: {age.std()}")
print(f"Product: {age.prod()}")

lineSpace()
data = np.arange(1, 17, dtype=int).reshape(4,4)
print(data)
print(data.max(axis=0))
print(data.max(axis=1))

Max age: 98
Min age: 82
Sum: 450
Mean: 90.0
STD: 5.329165037789691
Product: 5853229536


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[13 14 15 16]
[ 4  8 12 16]


In [ ]:
rng = np.random.default_rng()
print(rng.random((5,5)))
lineSpace()

rng_2 = np.random.default_rng()
print(rng.integers(10, size=(2, 5), endpoint=True)) #endpoint mean, include 10

[[0.42737812 0.63212343 0.96339518 0.86171928 0.38789191]
 [0.65723497 0.40980476 0.4281114  0.33328732 0.93374448]
 [0.35053265 0.67030819 0.29602573 0.97146677 0.99503115]
 [0.52302963 0.65819783 0.1267033  0.4766406  0.57407149]
 [0.12967119 0.30196639 0.4739995  0.4409697  0.18343651]]


[[ 9  6  6  5  7]
 [ 3  8 10  9  8]]


### UNIQUE ARRAY VALUES

In [ ]:
arr = np.array([1,1,1,2,3,4,4,5,66,4,3,3,2,4,5,5,3,2,2,4,56,4,3,22,2])

# 1️⃣ Unique values
print(np.unique(arr))  


# 2️⃣ Unique values + counts
print(np.unique(arr, return_counts=True))


# 3️⃣ Unique values + first index of each unique element
print(np.unique(arr, return_index=True))


# 4️⃣ Unique values + inverse indices
print(np.unique(arr, return_inverse=True))

[ 1  2  3  4  5 22 56 66]
(array([ 1,  2,  3,  4,  5, 22, 56, 66]), array([3, 5, 5, 6, 3, 1, 1, 1]))
(array([ 1,  2,  3,  4,  5, 22, 56, 66]), array([ 0,  3,  4,  5,  7, 23, 20,  8]))
(array([ 1,  2,  3,  4,  5, 22, 56, 66]), array([0, 0, 0, 1, 2, 3, 3, 4, 7, 3, 2, 2, 1, 3, 4, 4, 2, 1, 1, 3, 6, 3,
       2, 5, 1]))


### TRANSPOSE

In [ ]:
data = np.zeros((5,4))
data = data.transpose()
print(data)
print(data.shape)

data = data.transpose()
print(data)
print(data.shape)


# ----------------------------
# ----------------------------
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12],[13,14,15,16]])
print(arr_2d)
rever = np.transpose(arr_2d)
print(arr_2d.T)
print(rever)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(4, 5)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(5, 4)


### REVERSE 

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_array = np.flip(arr)
print(reversed_array)

print('Reversed Array: ', reversed_array)

[8 7 6 5 4 3 2 1]
Reversed Array:  [8 7 6 5 4 3 2 1]


In [ ]:
arr_2d = np.array(
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12],
        [13,14,15,16]
    ]
)

print(arr_2d)
multiLine()
rever = np.transpose(arr_2d)
print(arr_2d.T)
multiLine()
print(rever)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
11
